version: "2.3"
services:
  emby:
    image: emby/embyserver
    container_name: embyserver
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/Multimedia:/mnt/share1
    ports:
      - 8097:8096
      - 8921:8920
    restart: on-failure
