version: "3.7"
services:
  wps-office:
    image: lscr.io/linuxserver/wps-office:latest
    container_name: wps-office
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${APP_DATA_DIR}/config:/config
    ports:
      - 6100:3000
      - 6101:3001
    shm_size: "1gb"
    restart: unless-stopped
